name: SSH Login to Linux Machine

on:
  push:
    branches:
      - main

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client
        mkdir -p ~/.ssh
        echo "${{ secrets.WEB_TECH_18_KEY }}" > ~/.ssh/web-tech-18-key.pem
        chmod 600 ~/.ssh/web-tech-18-key.pem
        ssh-keyscan -H ec2-18-220-249-1.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: SSH Login
      run: |
        # copy over update script
        scp .github/scripts/update.sh ubuntu@ec2-18-220-249-1.us-east-2.compute.amazonaws.com:update.sh
        # run update script
        ssh -i ~/.ssh/web-tech-18-key.pem ubuntu@ec2-18-220-249-1.us-east-2.compute.amazonaws.com "bash update.sh" 

